### ISSUE TITLE
Error while npm start

### ISSUE THREAD

**Issue by ashishdhyani** [sebastiandeutsch/react-redux-starter#7]
I am getting below error while starting 

npm ERR! node v6.9.2
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! ReactReduxBoilerplate@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ReactReduxBoilerplate@0.0.1 start script 'node server.js'
.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ReactReduxBoilerplate
 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ReactReduxBoilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ReactReduxBoilerplate
npm ERR! There is likely additional logging output above.

**Comment by sebastiandeutsch** [comment]
Is it the complete error? Can it be that you're already running an application on Port `8000`?

I've tried it with npm 3 and 4 - no errors so far.

**Comment by ashishdhyani** [comment]
Full Error below

> ReactReduxBoilerplate@0.0.1 start E:\react-redux-starter
> node server.js

Listening at http://localhost:8000
E:\react-redux-starter\node_modules\enhanced-resolve\node_modules\memory-fs\lib\join.js:11
        if(absoluteWinRegExp.test(path)) return normalize(path + "\\" + request.replace(/\//g, "\\"));
                                                                               ^

TypeError: Cannot read property 'replace' of undefined
    at Tapable.join (E:\react-redux-starter\node_modules\enhanced-resolve\node_modules\memory-fs\lib\join.js:11:73)
    at Tapable.<anonymous> (E:\react-redux-starter\node_modules\enhanced-resolve\lib\FileAppendPlugin.js:14:19)
    at Tapable.applyPluginsParallelBailResult (E:\react-redux-starter\node_modules\tapable\lib\Tapable.js:139:14)
    at Tapable.doResolve (E:\react-redux-starter\node_modules\enhanced-resolve\lib\Resolver.js:83:15)
    at E:\react-redux-starter\node_modules\directory-named-webpack-plugin\index.js:52:17
    at Tapable.Resolver.forEachBail (E:\react-redux-starter\node_modules\enhanced-resolve\lib\Resolver.js:196:3)
    at E:\react-redux-starter\node_modules\directory-named-webpack-plugin\index.js:48:13
    at Storage.provide (E:\react-redux-starter\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.stat (E:\react-redux-starter\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:132:20)
    at Tapable.<anonymous> (E:\react-redux-starter\node_modules\directory-named-webpack-plugin\index.js:25:22)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ashish\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! ReactReduxBoilerplate@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ReactReduxBoilerplate@0.0.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ReactReduxBoilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ReactReduxBoilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ReactReduxBoilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\react-redux-starter\npm-debug.log
